name: "Fabrication"
on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**kibot.yaml'
    tags:
      - pcb*
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '**kibot.yaml'
  workflow_dispatch:
  workflow_call:

jobs:
  fabrication:
    uses: gcormier/kicad-jobs/.github/workflows/kicad-fabrication.yaml@main
    permissions:
      contents: write