name: "Fabrication"
on:
  push:
    paths:
      - 'pcb/**'
      - 'interface/**'
    tags:
      - pcb*
  pull_request:
    paths:
      - 'pcb/**'
      - 'interface/**'
  workflow_dispatch:
  workflow_call:

jobs:
  fabrication:
    uses: gcormier/kicad-jobs/.github/workflows/kicad-fabrication.yaml@main
    permissions:
      contents: write