name: "Fabrication - Panel"
on:

  workflow_dispatch:
  workflow_call:

jobs:
  fabrication-panel:
    uses: gcormier/kicad-jobs/.github/workflows/kicad-fabrication-panel-dev.yaml@main
    permissions:
      contents: write